### ISSUE TITLE
ONNX of EfficientPose

### ISSUE THREAD

**Issue by romygt** [Kaladin-Syl-WR/Hello_World#2]
I am using EfficientPose and I want to convert it to ONNX format to use it in Unity. Unfortunately, I am getting the same error as you. Can you please help me with this? I am really under pressure.

**Comment by Kaladin-Syl-WR** [comment]
Hi @romygt 

I really wish I could help, but I never figured out how to solve the problem. Would've helped if the guys at Onnx or EfficientPose answered, but I just don't know enough to figure it out and I had to move on to other work.
